version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app-hafiyanjye
    environment:
      - PORT=${PORT}
      - NODE_ENV={NODE_ENV}
      - DB_HOST={DB_HOST}
      - DB_PORT={DB_PORT}
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - JWT_SECRET={JWT_SECRET}
      - JWT_SIGN_OPTIONS={JWT_SIGN_OPTIONS}
      - JWT_ACCESS_TOKEN_TTL={JWT_ACCESS_TOKEN_TTL}
      - MAIL_NAME={MAIL_NAME}
      - MAIL_PASS={MAIL_PASS}
      - FRONTEND={FRONTEND}
    ports:
      - '3000:3000'
    networks:
      - shared-network
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - /usr/src/app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4password
    ports:
      - '5050:80'
    networks:
      - shared-network
    depends_on:
      - db
volumes:
  postgres:
networks:
  shared-network: